# Generated by Django 3.0.8 on 2020-08-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=50)),
                ('mobile_number', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('check_kakching', models.BooleanField()),
                ('address', models.CharField(max_length=200)),
                ('event', models.CharField(max_length=50)),
                ('event_date', models.DateField()),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
