# Generated by Django 3.0.8 on 2020-08-05 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costumer',
            old_name='check_kakching',
            new_name='from_kakching',
        ),
    ]
