# Generated by Django 3.0.8 on 2020-08-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200805_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='mobile_number',
            field=models.CharField(max_length=10),
        ),
    ]
