# Generated by Django 3.0.8 on 2020-08-15 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200806_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costumer',
            name='description',
        ),
    ]
