# Generated by Django 3.0.8 on 2020-08-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_invitation_invitee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='host',
            field=models.CharField(max_length=50),
        ),
    ]
